pluginManagement {
    repositories {
        // ================= ▼ 婉儿的终极修复：把阿里云仓库放在最前面！▼ =================
        maven { url 'https://maven.aliyun.com/repository/public' }
        // ================= ▲ 修复完毕！▲ =================
        gradlePluginPortal()
        mavenCentral()
        google()
        // ✨ 我们之前加的 chaquo 也要保留
        maven { url "https://chaquo.com/maven" }
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        // ================= ▼ 婉儿的终极修复：把阿里云仓库放在最前面！▼ =================
        maven { url 'https://maven.aliyun.com/repository/public' }
        // ================= ▲ 修复完毕！▲ =================
        mavenCentral()
        google()
        flatDir { dirs "$rootDir/app/libs" }
        maven { url "https://jitpack.io" }
        maven {
            url "http://4thline.org/m2"
            allowInsecureProtocol = true
        }
        // ✨ 我们之前加的 chaquo 也要保留
        maven { url "https://chaquo.com/maven" }
    }
}

include ':app'
include ':catvod'
include ':chaquo'
include ':quickjs'
rootProject.name = "TV"
